DROP TABLE IF EXISTS appointments;
DROP TABLE IF EXISTS availability_slots;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
                       id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       full_name     VARCHAR(100) NOT NULL,
                       email         VARCHAR(150) NOT NULL UNIQUE,
                       password_hash VARCHAR(255) NOT NULL,
                       created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE availability_slots (
                                    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    provider_name      VARCHAR(100) NOT NULL,
                                    start_date_time    TIMESTAMP NOT NULL,
                                    end_date_time      TIMESTAMP NOT NULL,
                                    marked_unavailable BOOLEAN NOT NULL DEFAULT FALSE,
                                    version            BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE appointments (
                              id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              slot_id            BIGINT NOT NULL UNIQUE,
                              patient_name       VARCHAR(100) NOT NULL,
                              user_id            BIGINT NOT NULL,
                              provider_name      VARCHAR(100) NOT NULL,
                              appointment_start  TIMESTAMP NOT NULL,
                              appointment_end    TIMESTAMP NOT NULL,
                              cancelled          BOOLEAN NOT NULL DEFAULT FALSE,
                              created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                              CONSTRAINT fk_appointments_slot
                                  FOREIGN KEY (slot_id) REFERENCES availability_slots(id),
                              CONSTRAINT fk_appointments_user
                                  FOREIGN KEY (user_id) REFERENCES users(id)
);